"""Download and install C++ standard library headers from LLVM releases.

Fetches the per-component ``libcxx-*.src.tar.xz`` tarball from GitHub
(typically ~2 MB) and extracts ``include/`` into
``<sdk>/usr/include/c++/v1/``.  Matching ``libc++.tbd`` and
``libc++abi.tbd`` stubs are generated so ``-lc++`` resolves at link time.
"""

from __future__ import annotations

import logging
import tarfile
from pathlib import Path
from urllib.request import urlopen, Request

logger = logging.getLogger(__name__)

# Maps Apple SDK version → LLVM release version used for libc++ headers.
# The exact match isn't critical — libc++ headers are backward-compatible
# and the cross-compiler handles version skew gracefully.
_LLVM_VERSIONS: dict[str, str] = {
    "15.0": "15.0.7",
    "15.2": "15.0.7",
    "16.0": "16.0.6",
    "17.0": "17.0.6",
    "18.0": "18.1.8",
    "18.2": "18.1.8",
}

_DEFAULT_LLVM_VERSION = "18.1.8"

_RELEASE_URL = (
    "https://github.com/llvm/llvm-project/releases/download/"
    "llvmorg-{version}/libcxx-{version}.src.tar.xz"
)


def install_libcxx_headers(
    sdk_root: Path,
    sdk_version: str,
    tbd_targets: list[str],
    cache_dir: Path,
) -> None:
    """Download libc++ headers and install them into the SDK."""
    llvm_version = _LLVM_VERSIONS.get(sdk_version, _DEFAULT_LLVM_VERSION)

    tar_path = _download_tarball(llvm_version, cache_dir)
    _extract_headers(tar_path, llvm_version, sdk_root)
    _generate_tbd_stubs(sdk_root, tbd_targets)

    logger.info(
        "Installed libc++ %s headers into %s/usr/include/c++/v1/",
        llvm_version, sdk_root,
    )


def _download_tarball(llvm_version: str, cache_dir: Path) -> Path:
    """Download the libcxx source tarball, caching to disk."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    cached = cache_dir / f"libcxx-{llvm_version}.src.tar.xz"
    if cached.exists():
        logger.debug("Using cached %s", cached)
        return cached

    url = _RELEASE_URL.format(version=llvm_version)
    logger.info("Downloading %s ...", url)

    req = Request(url, headers={"User-Agent": "apple-sdk-gen/1.0"})
    with urlopen(req, timeout=120) as resp:
        data = resp.read()

    cached.write_bytes(data)
    return cached


def _extract_headers(tar_path: Path, llvm_version: str, sdk_root: Path) -> None:
    """Extract libc++ headers from the tarball into usr/include/c++/v1/."""
    dst_root = sdk_root / "usr" / "include" / "c++" / "v1"
    dst_root.mkdir(parents=True, exist_ok=True)

    archive_prefix = f"libcxx-{llvm_version}.src/include/"

    with tarfile.open(tar_path, "r:xz") as tf:
        for member in tf:
            if not member.name.startswith(archive_prefix):
                continue
            if not member.isfile():
                continue

            rel = member.name[len(archive_prefix):]
            if not rel:
                continue
            # Skip build-system files
            if rel == "CMakeLists.txt" or rel.endswith(".cmake"):
                continue
            # Skip the config site template (needs CMake generation)
            if rel == "__config_site.in":
                continue

            dst = dst_root / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            f = tf.extractfile(member)
            if f is not None:
                dst.write_bytes(f.read())
                f.close()

    # Generate a minimal __config_site with Apple-compatible defaults
    config_site = dst_root / "__config_site"
    if not config_site.exists():
        config_site.write_text(
            "// Generated by apple-sdk-gen\n"
            "#ifndef _LIBCPP___CONFIG_SITE\n"
            "#define _LIBCPP___CONFIG_SITE\n"
            "#define _LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER\n"
            "#define _LIBCPP_ABI_VERSION 1\n"
            "#define _LIBCPP_ABI_NAMESPACE __1\n"
            "#endif\n"
        )

    logger.debug("Extracted libc++ headers from %s", tar_path.name)


def _generate_tbd_stubs(sdk_root: Path, tbd_targets: list[str]) -> None:
    """Generate libc++ and libc++abi TBD stubs."""
    usr_lib = sdk_root / "usr" / "lib"
    usr_lib.mkdir(parents=True, exist_ok=True)

    targets_str = ", ".join(tbd_targets)

    # ── libc++.tbd ───────────────────────────────────────────────────
    (usr_lib / "libc++.tbd").write_text(f"""\
--- !tapi-tbd
tbd-version:     4
targets:         [{targets_str}]
install-name:    '/usr/lib/libc++.1.dylib'
current-version: 1700.255.0
reexported-libraries:
  - targets:     [{targets_str}]
    libraries:
      - '/usr/lib/libc++abi.dylib'
...
""")

    # ── libc++abi.tbd ────────────────────────────────────────────────
    (usr_lib / "libc++abi.tbd").write_text(f"""\
--- !tapi-tbd
tbd-version:     4
targets:         [{targets_str}]
install-name:    '/usr/lib/libc++abi.dylib'
current-version: 1700.255.0
exports:
  - targets:     [{targets_str}]
    symbols:
      - ___cxa_allocate_exception
      - ___cxa_begin_catch
      - ___cxa_end_catch
      - ___cxa_free_exception
      - ___cxa_rethrow
      - ___cxa_throw
      - ___cxa_guard_acquire
      - ___cxa_guard_release
      - ___cxa_guard_abort
      - ___cxa_pure_virtual
      - ___cxa_deleted_virtual
      - ___cxa_atexit
      - ___cxa_finalize
      - ___cxa_demangle
      - ___cxa_current_exception_type
      - ___cxa_call_unexpected
      - ___cxa_decrement_exception_refcount
      - ___cxa_increment_exception_refcount
      - ___cxa_current_primary_exception
      - ___cxa_rethrow_primary_exception
      - ___cxa_throw_bad_array_new_length
      - ___cxa_uncaught_exceptions
      - ___gxx_personality_v0
      - __ZSt9terminatev
      - __ZSt13set_terminatePFvvE
      - __ZSt14get_unexpectedv
      - __ZSt13get_terminatev
      - __ZSt14set_unexpectedPFvvE
      - __ZSt10unexpectedv
      - __ZSt17current_exceptionv
      - __ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE
      - __ZSt18uncaught_exceptionv
      - __ZSt19uncaught_exceptionsv
      - __ZNSt9exceptionD2Ev
      - __ZNSt9exceptionD1Ev
      - __ZNSt9exceptionD0Ev
      - __ZNKSt9exception4whatEv
      - __ZNSt13bad_exceptionD2Ev
      - __ZNSt13bad_exceptionD1Ev
      - __ZNSt13bad_exceptionD0Ev
      - __ZNKSt13bad_exception4whatEv
      - __ZNSt9bad_allocD2Ev
      - __ZNSt9bad_allocD1Ev
      - __ZNSt9bad_allocD0Ev
      - __ZNKSt9bad_alloc4whatEv
      - __ZNSt20bad_array_new_lengthD2Ev
      - __ZNSt20bad_array_new_lengthD1Ev
      - __ZNSt20bad_array_new_lengthD0Ev
      - __ZNKSt20bad_array_new_length4whatEv
      - __ZNSt8bad_castD2Ev
      - __ZNSt8bad_castD1Ev
      - __ZNSt8bad_castD0Ev
      - __ZNKSt8bad_cast4whatEv
      - __ZNSt10bad_typeidD2Ev
      - __ZNSt10bad_typeidD1Ev
      - __ZNSt10bad_typeidD0Ev
      - __ZNKSt10bad_typeid4whatEv
      - __ZNSt13runtime_errorC1ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
      - __ZNSt13runtime_errorC2ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
      - __ZNSt13runtime_errorC1EPKc
      - __ZNSt13runtime_errorC2EPKc
      - __ZNSt13runtime_errorD2Ev
      - __ZNSt13runtime_errorD1Ev
      - __ZNSt13runtime_errorD0Ev
      - __ZNKSt13runtime_error4whatEv
      - __ZNSt11logic_errorC1ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
      - __ZNSt11logic_errorC2ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
      - __ZNSt11logic_errorC1EPKc
      - __ZNSt11logic_errorC2EPKc
      - __ZNSt11logic_errorD2Ev
      - __ZNSt11logic_errorD1Ev
      - __ZNSt11logic_errorD0Ev
      - __ZNKSt11logic_error4whatEv
      - __ZdlPv
      - __ZdlPvRKSt9nothrow_t
      - __ZdlPvm
      - __ZdlPvSt11align_val_t
      - __ZdlPvmSt11align_val_t
      - __ZdaPv
      - __ZdaPvRKSt9nothrow_t
      - __ZdaPvm
      - __ZdaPvSt11align_val_t
      - __ZdaPvmSt11align_val_t
      - __Znwm
      - __ZnwmRKSt9nothrow_t
      - __ZnwmSt11align_val_t
      - __ZnwmSt11align_val_tRKSt9nothrow_t
      - __Znam
      - __ZnamRKSt9nothrow_t
      - __ZnamSt11align_val_t
      - __ZnamSt11align_val_tRKSt9nothrow_t
      - __ZTISt9exception
      - __ZTISt13bad_exception
      - __ZTISt9bad_alloc
      - __ZTISt20bad_array_new_length
      - __ZTISt8bad_cast
      - __ZTISt10bad_typeid
      - __ZTISt13runtime_error
      - __ZTISt11logic_error
      - __ZTSSt9exception
      - __ZTSSt13bad_exception
      - __ZTSSt9bad_alloc
      - __ZTSSt20bad_array_new_length
      - __ZTSSt8bad_cast
      - __ZTSSt10bad_typeid
      - __ZTSSt13runtime_error
      - __ZTSSt11logic_error
...
""")

    logger.debug("Generated libc++ TBD stubs")
