"""Copy framework Headers/ and module.modulemap from a reference SDK.

The synthetic headers generated by apple-sdk-gen from the documentation API
may include incorrect cross-framework imports (e.g. Foundation importing
Distributed, UIKit importing AppKit) that don't exist on the target platform.
This supplement copies the real framework headers from a reference SDK,
which have correct platform-conditional imports.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path

from ..config import PLATFORM_CONFIGS

logger = logging.getLogger(__name__)


def install_reference_framework_headers(
    sdk_root: Path,
    platform_key: str,
    reference_root: Path,
) -> None:
    """Copy framework ``Headers/`` and ``module.modulemap`` from the reference SDK."""
    cfg = PLATFORM_CONFIGS.get(platform_key)
    if cfg is None:
        logger.warning("Unknown platform %s, skipping reference framework headers", platform_key)
        return

    ref_sdk = (
        reference_root / "Xcode.app" / "Contents" / "Developer" / "Platforms"
        / cfg.platform_dir / "Developer" / "SDKs" / f"{cfg.sdk_prefix}.sdk"
    )
    if not ref_sdk.is_dir():
        ref_sdk = (
            reference_root / "Contents" / "Developer" / "Platforms"
            / cfg.platform_dir / "Developer" / "SDKs" / f"{cfg.sdk_prefix}.sdk"
        )
    if not ref_sdk.is_dir():
        logger.warning("Reference SDK not found at %s", ref_sdk)
        return

    ref_frameworks = ref_sdk / "System" / "Library" / "Frameworks"
    if not ref_frameworks.is_dir():
        logger.warning("No System/Library/Frameworks/ in reference SDK %s", ref_sdk)
        return

    dst_frameworks = sdk_root / "System" / "Library" / "Frameworks"
    copied_headers = 0
    copied_modulemaps = 0

    for fw_dir in sorted(ref_frameworks.iterdir()):
        if not fw_dir.is_dir() or not fw_dir.name.endswith(".framework"):
            continue

        dst_fw = dst_frameworks / fw_dir.name
        if not dst_fw.is_dir():
            continue  # Only copy headers for frameworks we generated

        # Copy Headers/ directory
        ref_headers = fw_dir / "Headers"
        if ref_headers.is_dir():
            dst_headers = dst_fw / "Headers"
            if dst_headers.exists():
                shutil.rmtree(dst_headers)
            shutil.copytree(ref_headers, dst_headers, symlinks=True)
            copied_headers += 1

        # Copy module.modulemap from Modules/
        ref_modules = fw_dir / "Modules"
        if ref_modules.is_dir():
            ref_modulemap = ref_modules / "module.modulemap"
            if ref_modulemap.is_file():
                dst_modules = dst_fw / "Modules"
                dst_modules.mkdir(parents=True, exist_ok=True)
                dst_modulemap = dst_modules / "module.modulemap"
                shutil.copy2(ref_modulemap, dst_modulemap)
                copied_modulemaps += 1

    # Also copy SubFrameworks/ (e.g. UIUtilities) from the reference SDK
    ref_subframeworks = ref_sdk / "System" / "Library" / "SubFrameworks"
    if ref_subframeworks.is_dir():
        dst_subframeworks = sdk_root / "System" / "Library" / "SubFrameworks"
        if dst_subframeworks.exists():
            shutil.rmtree(dst_subframeworks)
        shutil.copytree(ref_subframeworks, dst_subframeworks, symlinks=True)

    logger.info(
        "Copied %d framework Headers/ dirs and %d module.modulemaps from %s",
        copied_headers, copied_modulemaps, ref_sdk,
    )
