from __future__ import annotations

import logging
from collections import defaultdict

from ..models.availability import availability_macro, deprecated_macro
from ..models.symbol import Symbol
from ..models.types import SymbolKind

logger = logging.getLogger(__name__)

# Compatibility macros needed for generated headers
COMPAT_PREAMBLE = """\
#pragma once

#import <Foundation/NSObjCRuntime.h>

#ifndef API_AVAILABLE
#define API_AVAILABLE(...)
#endif
#ifndef API_DEPRECATED
#define API_DEPRECATED(...)
#endif
#ifndef API_UNAVAILABLE
#define API_UNAVAILABLE(...)
#endif
#ifndef NS_ASSUME_NONNULL_BEGIN
#define NS_ASSUME_NONNULL_BEGIN
#endif
#ifndef NS_ASSUME_NONNULL_END
#define NS_ASSUME_NONNULL_END
#endif
#ifndef NS_SWIFT_NAME
#define NS_SWIFT_NAME(x)
#endif
#ifndef NS_REFINED_FOR_SWIFT
#define NS_REFINED_FOR_SWIFT
#endif
#ifndef NS_SWIFT_UNAVAILABLE
#define NS_SWIFT_UNAVAILABLE(x)
#endif
#ifndef NS_ENUM
#define NS_ENUM(_type, _name) enum _name : _type _name; enum _name : _type
#endif
#ifndef NS_OPTIONS
#define NS_OPTIONS(_type, _name) enum _name : _type _name; enum _name : _type
#endif
#ifndef NS_CLOSED_ENUM
#define NS_CLOSED_ENUM(_type, _name) enum _name : _type _name; enum _name : _type
#endif
#ifndef NS_TYPED_ENUM
#define NS_TYPED_ENUM
#endif
#ifndef NS_TYPED_EXTENSIBLE_ENUM
#define NS_TYPED_EXTENSIBLE_ENUM
#endif
"""


def generate_umbrella_header(
    framework_name: str,
    symbols: list[Symbol],
    all_symbols: dict[str, Symbol] | None = None,
) -> str:
    """Generate the main umbrella header for a framework."""
    lines: list[str] = []
    lines.append(f"// {framework_name}.h - Generated by apple-sdk-gen")
    lines.append(f"// This is a stub header for cross-compilation")
    lines.append("")
    lines.append(COMPAT_PREAMBLE)
    lines.append("")

    # Collect imports for cross-framework references
    imports = _collect_imports(symbols, framework_name)
    for imp in sorted(imports):
        lines.append(f"#import <{imp}/{imp}.h>")
    if imports:
        lines.append("")

    # Group symbols by kind for proper ordering
    groups = _group_symbols(symbols)

    # Forward declarations
    forward_classes = set()
    forward_protocols = set()
    for sym in symbols:
        if sym.kind == SymbolKind.CLASS:
            forward_classes.add(sym.objc_name)
        elif sym.kind == SymbolKind.PROTOCOL:
            forward_protocols.add(sym.objc_name)

    if forward_classes:
        for cls in sorted(forward_classes):
            lines.append(f"@class {cls};")
        lines.append("")

    if forward_protocols:
        for proto in sorted(forward_protocols):
            lines.append(f"@protocol {proto};")
        lines.append("")

    # Emit typedefs and enums first
    for sym in groups.get("typedef", []):
        decl = _render_symbol_declaration(sym)
        if decl:
            lines.append(decl)
            lines.append("")

    for sym in groups.get("enum", []):
        decl = _render_symbol_declaration(sym)
        if decl:
            lines.append(decl)
            lines.append("")

    # Emit global variables
    for sym in groups.get("var", []):
        decl = _render_symbol_declaration(sym)
        if decl:
            lines.append(decl)
            lines.append("")

    # Emit global functions
    for sym in groups.get("func", []):
        decl = _render_symbol_declaration(sym)
        if decl:
            lines.append(decl)
            lines.append("")

    # Emit protocols
    for sym in groups.get("protocol", []):
        block = _render_interface_block(sym, symbols, all_symbols)
        if block:
            lines.append(block)
            lines.append("")

    # Emit classes
    for sym in groups.get("class", []):
        block = _render_interface_block(sym, symbols, all_symbols)
        if block:
            lines.append(block)
            lines.append("")

    # Emit structs
    for sym in groups.get("struct", []):
        decl = _render_symbol_declaration(sym)
        if decl:
            lines.append(decl)
            lines.append("")

    return "\n".join(lines)


def _collect_imports(symbols: list[Symbol], framework_name: str) -> set[str]:
    imports: set[str] = set()
    for sym in symbols:
        for rel in sym.relationships:
            for ident in rel.identifiers:
                if "com.externally.resolved.symbol" in ident:
                    continue
                if "/documentation/" in ident:
                    parts = ident.split("/documentation/", 1)[1].split("/")
                    if parts and parts[0].lower() != framework_name.lower():
                        imports.add(parts[0])
    # Always import Foundation for non-Foundation frameworks
    if framework_name != "Foundation" and framework_name != "ObjectiveC":
        imports.add("Foundation")
    return imports


def _group_symbols(symbols: list[Symbol]) -> dict[str, list[Symbol]]:
    groups: dict[str, list[Symbol]] = defaultdict(list)
    seen: set[str] = set()
    for sym in symbols:
        if not sym.is_objc:
            continue
        # Deduplicate by identifier
        key = sym.identifier or sym.title
        if key in seen:
            continue
        seen.add(key)

        if sym.kind == SymbolKind.CLASS:
            groups["class"].append(sym)
        elif sym.kind == SymbolKind.PROTOCOL:
            groups["protocol"].append(sym)
        elif sym.kind == SymbolKind.ENUM:
            groups["enum"].append(sym)
        elif sym.kind in (SymbolKind.TYPEALIAS, SymbolKind.TYPEDEF):
            groups["typedef"].append(sym)
        elif sym.kind == SymbolKind.FUNC:
            groups["func"].append(sym)
        elif sym.kind == SymbolKind.VAR:
            groups["var"].append(sym)
        elif sym.kind == SymbolKind.STRUCT:
            groups["struct"].append(sym)
    return groups


def _render_symbol_declaration(sym: Symbol) -> str | None:
    if not sym.objc_declaration:
        return None

    decl_text = sym.objc_declaration.render().strip()
    if not decl_text:
        return None

    avail = availability_macro(sym)
    dep = deprecated_macro(sym)
    suffix = ""
    if dep:
        suffix = f" {dep}"
    elif avail:
        suffix = f" {avail}"

    # Ensure declaration ends with semicolon if it's a simple decl
    if not decl_text.endswith(";") and not decl_text.endswith("}"):
        decl_text += ";"

    return f"{decl_text}{suffix}"


def _render_interface_block(
    sym: Symbol,
    all_framework_symbols: list[Symbol],
    all_symbols: dict[str, Symbol] | None = None,
) -> str | None:
    if not sym.is_objc:
        return None

    lines: list[str] = []
    avail = availability_macro(sym)
    avail_str = f" {avail}" if avail else ""

    if sym.kind == SymbolKind.PROTOCOL:
        lines.append(f"@protocol {sym.objc_name}{avail_str}")
    elif sym.kind == SymbolKind.CLASS:
        superclass = _resolve_superclass(sym)
        protocols = _resolve_protocols(sym)
        proto_str = f" <{', '.join(protocols)}>" if protocols else ""
        if superclass:
            lines.append(f"@interface {sym.objc_name} : {superclass}{proto_str}{avail_str}")
        else:
            lines.append(f"@interface {sym.objc_name}{proto_str}{avail_str}")
    else:
        return None

    # Find child members
    children = _find_children(sym, all_framework_symbols, all_symbols)
    for child in children:
        if not child.objc_declaration:
            continue
        child_decl = child.objc_declaration.render().strip()
        if not child_decl:
            continue
        child_avail = availability_macro(child)
        child_suffix = f" {child_avail}" if child_avail else ""
        if not child_decl.endswith(";"):
            child_decl += ";"
        lines.append(f"{child_decl}{child_suffix}")

    lines.append("@end")
    return "\n".join(lines)


def _resolve_superclass(sym: Symbol) -> str | None:
    for rel in sym.relationships:
        if rel.kind == "inheritsFrom":
            for ident in rel.identifiers:
                # Extract class name from identifier
                if "c:objc(cs)" in ident:
                    return ident.split("c:objc(cs)")[-1]
                # Try to extract from doc path
                if "/documentation/" in ident:
                    parts = ident.split("/")
                    return parts[-1]
    return None


def _resolve_protocols(sym: Symbol) -> list[str]:
    protocols = []
    for rel in sym.relationships:
        if rel.kind == "conformsTo":
            for ident in rel.identifiers:
                if "c:objc(pl)" in ident:
                    protocols.append(ident.split("c:objc(pl)")[-1])
                elif "/documentation/" in ident:
                    parts = ident.split("/")
                    name = parts[-1]
                    # Only include if it looks like a protocol name
                    if name and name[0].isupper():
                        protocols.append(name)
    return protocols


def _normalize_path(identifier: str) -> str:
    """Extract and normalize the documentation path for comparison.

    Handles both formats:
    - doc://com.apple.foundation/documentation/Foundation/NSString/length
    - /documentation/foundation/nsstring/length
    """
    if "/documentation/" in identifier:
        path = "/documentation/" + identifier.split("/documentation/", 1)[1]
    else:
        path = identifier
    return path.lower().rstrip("/")


def _find_children(
    parent: Symbol,
    all_framework_symbols: list[Symbol],
    all_symbols: dict[str, Symbol] | None = None,
) -> list[Symbol]:
    child_paths_normalized = {_normalize_path(cp) for cp in parent.children}

    children: list[Symbol] = []
    seen: set[str] = set()

    for sym in all_framework_symbols:
        if not sym.identifier:
            continue
        norm = _normalize_path(sym.identifier)
        if norm in child_paths_normalized and norm not in seen:
            seen.add(norm)
            children.append(sym)

    if all_symbols:
        for cp in parent.children:
            norm = _normalize_path(cp)
            if norm in seen:
                continue
            if norm in all_symbols:
                seen.add(norm)
                children.append(all_symbols[norm])

    return children
